# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^inventory/intended/.*
      - id: check-added-large-files

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.3.2
    hooks:
      - id: ansible-lint
        exclude: ^inventory/intended/.*
        files: \.(yaml|yml)$
