plugins:
  - jekyll-relative-links
theme: jekyll-theme-minimal
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - doc/devices/SPINE101.md
  - doc/devices/SPINE102.md
  - doc/devices/LEAF101.md
  - doc/devices/LEAF102.md
  - doc/devices/LEAFB101.md
  - doc/devices/LEAFB102.md
  - doc/devices/BLEAF101.md
  - doc/devices/BLEAF102.md

