---
- name: Create required output directories if not present
  tags: [build, provision]
  file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{ structured_dir }}"
    - "{{ documentation_dir }}"
    - "{{ eos_config_dir }}"
    - "{{ devices_dir }}"
    - "{{ fabric_dir }}"
  delegate_to: localhost
  run_once: true

- name: Check if structure configuration file exists
  tags: [build, provision]
  stat:
    path: "{{ structured_dir }}/{{ inventory_hostname }}.yml"
  register: stat_result
  delegate_to: localhost
  when: structured_config is not defined

- name: Set AVD facts
  tags: [build, provision]
  arista.avd.yaml_templates_to_facts:
    templates: "{{ templates.facts }}"
  delegate_to: localhost
  check_mode: false
  changed_when: false


- name: Set AVD topology facts
  tags: [build, provision]
  arista.avd.yaml_templates_to_facts:
    templates: "{{ templates.topology_facts }}"
  delegate_to: localhost
  check_mode: false
  changed_when: false

- name: Include device intended structure configuration variables
  tags: [build, provision]
  include_vars: "{{ structured_dir }}/{{ inventory_hostname }}.yml"
  delegate_to: localhost
  when: structured_config is not defined and stat_result.stat.exists

- name: Include compare config
  tags: [build, provision]
  include_vars: "{{ structured_dir }}/compare.yml"
  delegate_to: localhost
  when: structured_config is not defined and stat_result.stat.exists

- name: new README
  run_once: true
  tags: [build, provision, documentation, test]
  copy:
    content: "{{ lookup('template','Readme.md.j2') }}"
    dest: "README.md"
    mode: 0664

- name: new Githubpages
  tags: [build, provision, documentation, test]
  run_once: true
  copy:
    content: "{{ lookup('template','_config.yml.j2') }}"
    dest: "_config.yml"
    mode: 0664


- name: new doc
  tags: [build, provision, documentation, test]
  copy:
    content: "{{ lookup('template','san_device_doc.j2') }}"
    dest: "{{ devices_dir }}/{{ inventory_hostname }}.md"
    mode: 0664

- name: Generate fabric documentation
  tags: [build, provision, documentation]
  delegate_to: localhost
  check_mode: false
  copy:
    content: "{{ lookup('template','fabric/documentation/fabric-documentation.j2') }}"
    dest: "{{ fabric_dir }}/{{ fabric_name }}-documentation.md"
    mode: 0664
