- name: Clean configuration
  hosts: localhost
  connection: local
  tasks:
    - name: Ansible delete file glob
      find:
        paths: doc/devices/compare/
        patterns: "*.cfg"
      register: files_to_delete
    - name: Ansible remove file glob
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ files_to_delete.files }}"

- name: "Compare configs"
  hosts: GLOBAL
  connection: local
  tasks:
    - name: "Check config"
      command: "python3 scripts/api.py \
              -a inventory/intended/configs/{{ inventory_hostname }}.cfg \
              -b doc/devices/configs/{{ inventory_hostname }}.cfg \
              -f doc/devices/compare/{{ inventory_hostname }}.html"
      register: "output"
      changed_when: output.rc != 0
    - name: Debug variables
      debug: var=output.stdout_lines
