---
- name: GENERATE CONFIG AND DOCUMENTATION AZ1
  hosts: AZ1
  tasks:
    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs
    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen
    - name: deploy configuration to device
      tags: [deploy, never]
      import_role:
        name: arista.avd.eos_config_deploy_eapi
    - name: Debug variables
      debug: var=output.stdout_lines
- name: "COPY TO DHCPD AZ1 CONFIGS"
  hosts: localhost
  connection: local
  tags: [build]
  tasks:
    - name: "Copy init files to tftboot"
      shell: "cp -rp ../inventory/intended/configs/* /var/tftpboot/"
      register: "output"
      changed_when: output.rc != 0
    - name: Debug variables
      debug: var=output.stdout_lines
- name: GENERATE CONFIG AND DOCUMENTATION AZ2
  hosts: AZ2
  tasks:
    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs
    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen
    - name: deploy configuration to device
      tags: [deploy, never]
      import_role:
        name: arista.avd.eos_config_deploy_eapi
- name: "COPY TO DHCPD AZ2 CONFIGS"
  hosts: localhost
  connection: local
  tags: [build]
  tasks:
    - name: "Copy init files to tftboot"
      shell: "cp -rp ../inventory/intended/configs/* /var/tftpboot/"
      register: "output"
      changed_when: output.rc != 0
    - name: Show chages
      debug: var=output.stdout_lines

- name: Create Doc AZ1
  hosts: AZ1
  tags: [build]
  roles:
     - role: san_doc_avd

- name: Create Doc AZ2
  hosts: AZ2
  tags: [build]  
  roles:
     - role: san_doc_avd

