---
servers:
  VPC201:
    rack: RackA
    adapters:
      - type: nic
        rack: Virtual-1
        server_ports: [VPC201-nic0]
        switch_ports: [Ethernet1]
        switches: [LEAFA201]
        enabled: true
        mode: access
        vlans: 17
        spanning_tree_portfast: edge

  f5:
    rack: RackB
    adapters:
      - type: nic
        rack: Virtual-2
        server_ports: [uplink]
        switch_ports: [Ethernet10]
        switches: [LEAFA202]
        enabled: true
        mode: access
        vlans: 15
        spanning_tree_portfast: edge
      - type: nic
        rack: Virtual-2
        server_ports: [downlinks]
        switch_ports: [Ethernet11]
        switches: [LEAFA202]
        enabled: true
        mode: access
        vlans: 17
        spanning_tree_portfast: edge

  VPCServer1:
    rack: RackB
    adapters:
      - type: nic
        rack: Virtual-1
        server_ports: [eth0]
        switch_ports: [Ethernet5]
        switches: [LEAFA202]
        enabled: true
        mode: access
        vlans: 17
        spanning_tree_portfast: edge
