# This is a basic workflow to help you get started with Actions

name: CI Develop

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - 'develop'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: lab
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Checking Code...
      run: |

        pre-commit run --hook-stage commit --files ./roles/* ./playbooks/* ./inventory/* 

    - name: Checking Ansible configuration...
      run: |
        echo ${{ secrets.VAULT_PASSWORD }} >> .vault      
        ansible-playbook playbooks/fabric-deploy-All.yml -i inventory/ -t build --vault-password-file .vault

    - name: Genereting doc...
      run: |
        ansible-playbook playbooks/generate_doc.yml -i inventory/ --vault-password-file .vault

    - name: Commiting new doc...
      uses: EndBug/add-and-commit@v9.0.0
      with:
        message: "[Actions] Doc autogenerate"


  cd:
    # The type of runner that the job will run on
    runs-on: lab
    needs: ci
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generating Code...
      run: |
        echo 

    - name: Deploying Code on LAB101...
      run: |
        echo "Deploying.."


