name: Release documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - 'main'


env:
  ACTION_GITHUB_TAG_ACTION: v5.5
  PACKER_VERSION: "1.7.2"
  APPLICATION_ID: "120620"
  PLAYBOOK_VERSION: "V0.5.4"
  PROJECT: ccd_network_product_1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  upload-assests:
    # The type of runner that the job will run on
    runs-on: lab
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: Create zip file
      run: tar -cvzf ${{ env.PROJECT }}_configs.tar.gz inventory/intended/configs/

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ GITHUB.token }}
      with:
        upload_url: ${{ needs.build.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ${{ env.PROJECT }}_configs.zip
        asset_name: ${{ env.PROJECT }}_configs.zip
        asset_content_type: application/zip
